version: "3.7"

services:
  django-service:
    image: python:3.8
    build: ./api_Django
    container_name: django-service
    ports:
      - "8000:8000"
    volumes:
      - ./api_Django:/app_django

    command: python api/manage.py runserver 0.0.0.0:8000

  express-service:
    image: node:20.12.0
    build: ./api_express
    container_name: express-service
    ports:
      - "3002:3002"
    volumes:
      - ./api_express:/app_express
    command: npm start

  api-gateway:
    image: nginx
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    depends_on:
      #- django-service
      - express-service
